version: "3.9"
services:
  minecraft:
    image: "als3bas/graalvm-papermc:1.19"
    restart: always
    container_name: "mcserver"
    environment:
      MEMORYSIZE: "10G"
      PAPERMC_FLAGS: ""
      TZ: "America/Santiago"
    volumes:
      - "./:/data:rw"
    ports:
      - "25565:25565"
    # The following allow `docker attach minecraft` to work
    stdin_open: true
    tty: true
